functional:
  - Пользователь может зарегистрироваться через email или социальные сети
  - Восстановление пароля через email
  - Видеть статистику решенных задач, рейтинг, участие в соревнованиях
  - Возможность редактирования профиля
  - Переключение языка в задаче 
  - Возможность создания игры одной кнопкой "Create game"
  - Присоединение пользователей к открытым баттлам
  - Таймер обратного отсчета во время соревнования
  - Автоматическая проверка решения
  - Онлайн-редактор кода с подсветкой синтаксиса
  - Возможность выбора языка программирования
  - Уведомления о начале и окончании соревнований
  - Отображение текущих результатов соревнования
  - История прошлых баттлов и личный рейтинг
  - Просмотр прогресса соперника в реальном времени во время баттла
  - Возможность играть против бота 
  - Отображение времени выполнения кода
  - Отображение изменения рейтинга после баттла
  - Кнопка "Run" для проверки решения во время баттла
  - Неограниченное количество попыток проверки решения
  - Возможность повторного подключения к баттлу после отключения
  - Проверка интерфейса после победы
  - Отображение интерфейса для проигравшего
  - Появление кнопки "Back to Home"  у победителя после завершения игры
  - Деактивация кнопки "Run" после завершения игры
  - Возможность просмотра своего кода после завершения баттла
  - Проверка функциональности кнопки "Rematch" после завершения баттла
  - Проверка функциональности кнопки "Back to Home" после завершения баттла
  - Проверка, что после выхода через "Back to Home" нельзя вернуться в прошлый баттл по прямой ссылке
non-functional:
  - Интуитивно понятный интерфейс
  - Дружелюбный UX/UI дизайн
  - Быстрая загрузка страниц
  - Шифрование данных (HTTPS, TLS)
  - Защита от XSS, SQL-injection и других типовых уязвимостей
  - Полностью адаптивный дизайн
  - Упрощенный интерфейс для мобильных устройств
  - Корректное отображение редактора кода на небольших экранах
  - Поддержка последних версий всех популярных браузеров

implicit:
  - Сайт должен быть доступен пользователям по общедоступному URL
  - Сайт продолжает работать при случайном обновлении страницы во время баттла
