functional:
  - Пользователь может зарегистрироваться через email или социальные сети
  - Восстановление пароля через email
  - Отображение статистики: количество решенных задач, рейтинг, участие в соревнованиях
  - Возможность редактирования профиля
  - Переключение языка в задаче 
  - Присоединение пользователей к открытым баттлам
  - Таймер обратного отсчета во время соревнования
  - Автоматическая проверка решения
  - Онлайн-редактор кода с подсветкой синтаксиса
  - Возможность выбора языка программирования
  - Уведомления о начале и окончании соревнований
  - Отображение текущих результатов соревнования
  - История прошлых баттлов и личный рейтинг
  
non-functional:
  - Интуитивно понятный интерфейс
  - Дружелюбный UX/UI дизайн
  - Быстрая загрузка страниц
  - Шифрование данных (HTTPS, TLS)
  - Защита от XSS, SQL-injection и других типовых уязвимостей
  - Полностью адаптивный дизайн
  - Упрощенный интерфейс для мобильных устройств
  - Корректное отображение редактора кода на небольших экранах
  - Поддержка последних версий всех популярных браузеров
  - Отказоустойчивая система способная выдержать нагрузку минимум 1000 подключений одновременно

implicit:
  - Сайт должен быть доступен 24/7
  - Сайт должен быть доступен пользователям по общедоступному URL
  - Должна соблюдаться базовая правовая база, связанная с онлайн-сервисами
